! Automatically generated file.  Do not edit!

  module arrays

  integer, allocatable, dimension(:) :: s
  real(8), allocatable, dimension(:) :: t
  real(8), allocatable, dimension(:) :: t1
  real(8), allocatable, dimension(:) :: t2
  real(8), allocatable, dimension(:) :: dr
  real(8), allocatable, dimension(:) :: dt

  real(8), dimension (:,:,:), pointer :: grabvar_bound

  character(50), allocatable, dimension(:) :: outvars0Darray
  character(50), allocatable, dimension(:) :: outvars1Darray
  real(8), dimension (:), pointer :: syncvar
  real(8), dimension (:,:), pointer :: diffvar
  real(8), dimension (:,:), pointer :: intvar
  real(8), dimension (:,:), pointer :: savevar
  real(8), dimension (:,:), pointer :: interpvar
  real(8), dimension (:,:), pointer :: restrictvar
  real(8), dimension (:,:), pointer :: dissipvar
  real(8), dimension (:,:), pointer :: sourcevar
  real(8), dimension (:), pointer :: savevar0D
  real(8), allocatable, dimension (:,:), target :: auxarray
  real(8), allocatable, dimension (:,:), target :: auxarray2
  real(8), allocatable, dimension (:,:), target :: r
  real(8), allocatable, dimension (:,:), target :: r_area
  real(8), allocatable, dimension (:,:), target :: D1_r_area
  real(8), allocatable, dimension (:,:), target :: alpha
  real(8), allocatable, dimension (:,:), target :: alpha_p
  real(8), allocatable, dimension (:,:), target :: alpha_a
  real(8), allocatable, dimension (:,:), target :: salpha
  real(8), allocatable, dimension (:,:,:), target :: alpha_bound
  real(8), allocatable, dimension (:,:), target :: D1_alpha
  real(8), allocatable, dimension (:,:), target :: D2_alpha
  real(8), allocatable, dimension (:,:), target :: DA_alpha
  real(8), allocatable, dimension (:,:), target :: Dcov2_alpha
  real(8), allocatable, dimension (:,:), target :: Lapla_alpha
  real(8), allocatable, dimension (:,:), target :: DD_alphar
  real(8), allocatable, dimension (:,:), target :: falpha
  real(8), allocatable, dimension (:), target :: tau_origin
  real(8), allocatable, dimension (:), target :: tau_origin_p
  real(8), allocatable, dimension (:), target :: tau_origin_a
  real(8), allocatable, dimension (:), target :: stau_origin
  real(8), allocatable, dimension (:,:), target :: beta
  real(8), allocatable, dimension (:,:), target :: beta_p
  real(8), allocatable, dimension (:,:), target :: beta_a
  real(8), allocatable, dimension (:,:), target :: sbeta
  real(8), allocatable, dimension (:,:,:), target :: beta_bound
  real(8), allocatable, dimension (:,:), target :: D1_beta
  real(8), allocatable, dimension (:,:), target :: D2_beta
  real(8), allocatable, dimension (:,:), target :: DA_beta
  real(8), allocatable, dimension (:,:), target :: dtbeta
  real(8), allocatable, dimension (:,:), target :: dtbeta_p
  real(8), allocatable, dimension (:,:), target :: dtbeta_a
  real(8), allocatable, dimension (:,:), target :: sdtbeta
  real(8), allocatable, dimension (:,:,:), target :: dtbeta_bound
  real(8), allocatable, dimension (:,:), target :: D1_dtbeta
  real(8), allocatable, dimension (:,:), target :: DA_dtbeta
  real(8), allocatable, dimension (:,:), target :: DIV_beta
  real(8), allocatable, dimension (:,:), target :: D1_DIV_beta
  real(8), allocatable, dimension (:,:), target :: DD_beta
  real(8), allocatable, dimension (:,:), target :: fdriver
  real(8), allocatable, dimension (:,:), target :: fdriver_p
  real(8), allocatable, dimension (:,:), target :: fdriver_a
  real(8), allocatable, dimension (:,:), target :: sfdriver
  real(8), allocatable, dimension (:,:,:), target :: fdriver_bound
  real(8), allocatable, dimension (:,:), target :: D1_fdriver
  real(8), allocatable, dimension (:,:), target :: DA_fdriver
  real(8), allocatable, dimension (:,:), target :: phi
  real(8), allocatable, dimension (:,:), target :: phi_p
  real(8), allocatable, dimension (:,:), target :: phi_a
  real(8), allocatable, dimension (:,:), target :: sphi
  real(8), allocatable, dimension (:,:,:), target :: phi_bound
  real(8), allocatable, dimension (:,:), target :: D1_phi
  real(8), allocatable, dimension (:,:), target :: D2_phi
  real(8), allocatable, dimension (:,:), target :: DA_phi
  real(8), allocatable, dimension (:,:), target :: psi
  real(8), allocatable, dimension (:,:), target :: psi2
  real(8), allocatable, dimension (:,:), target :: psi4
  real(8), allocatable, dimension (:,:), target :: D1_psi
  real(8), allocatable, dimension (:,:), target :: D2_psi
  real(8), allocatable, dimension (:,:), target :: chi
  real(8), allocatable, dimension (:,:), target :: chi_p
  real(8), allocatable, dimension (:,:), target :: chi_a
  real(8), allocatable, dimension (:,:), target :: schi
  real(8), allocatable, dimension (:,:,:), target :: chi_bound
  real(8), allocatable, dimension (:,:), target :: D1_chi
  real(8), allocatable, dimension (:,:), target :: D2_chi
  real(8), allocatable, dimension (:,:), target :: DA_chi
  real(8), allocatable, dimension (:,:), target :: DD_phir
  real(8), allocatable, dimension (:,:), target :: A
  real(8), allocatable, dimension (:,:), target :: A_p
  real(8), allocatable, dimension (:,:), target :: A_a
  real(8), allocatable, dimension (:,:), target :: sA
  real(8), allocatable, dimension (:,:,:), target :: A_bound
  real(8), allocatable, dimension (:,:), target :: D1_A
  real(8), allocatable, dimension (:,:), target :: D2_A
  real(8), allocatable, dimension (:,:), target :: B
  real(8), allocatable, dimension (:,:), target :: B_p
  real(8), allocatable, dimension (:,:), target :: B_a
  real(8), allocatable, dimension (:,:), target :: sB
  real(8), allocatable, dimension (:,:,:), target :: B_bound
  real(8), allocatable, dimension (:,:), target :: D1_B
  real(8), allocatable, dimension (:,:), target :: D2_B
  real(8), allocatable, dimension (:,:), target :: DA_A
  real(8), allocatable, dimension (:,:), target :: DA_B
  real(8), allocatable, dimension (:,:), target :: DD_Ar
  real(8), allocatable, dimension (:,:), target :: DD_Br
  real(8), allocatable, dimension (:,:), target :: APHYS
  real(8), allocatable, dimension (:,:), target :: BPHYS
  real(8), allocatable, dimension (:,:), target :: AB2
  real(8), allocatable, dimension (:,:), target :: D1_AB2
  real(8), allocatable, dimension (:,:), target :: D2_AB2
  real(8), allocatable, dimension (:,:), target :: GRR
  real(8), allocatable, dimension (:,:), target :: hembed
  real(8), allocatable, dimension (:,:), target :: trK
  real(8), allocatable, dimension (:,:), target :: trK_p
  real(8), allocatable, dimension (:,:), target :: trK_a
  real(8), allocatable, dimension (:,:), target :: strK
  real(8), allocatable, dimension (:,:,:), target :: trK_bound
  real(8), allocatable, dimension (:,:), target :: D1_trK
  real(8), allocatable, dimension (:,:), target :: DA_trK
  real(8), allocatable, dimension (:,:), target :: KTA
  real(8), allocatable, dimension (:,:), target :: KTA_p
  real(8), allocatable, dimension (:,:), target :: KTA_a
  real(8), allocatable, dimension (:,:), target :: sKTA
  real(8), allocatable, dimension (:,:,:), target :: KTA_bound
  real(8), allocatable, dimension (:,:), target :: D1_KTA
  real(8), allocatable, dimension (:,:), target :: DA_KTA
  real(8), allocatable, dimension (:,:), target :: KTB
  real(8), allocatable, dimension (:,:), target :: D1_KTB
  real(8), allocatable, dimension (:,:), target :: DA_KTB
  real(8), allocatable, dimension (:,:), target :: KAPHYS
  real(8), allocatable, dimension (:,:), target :: KBPHYS
  real(8), allocatable, dimension (:,:), target :: K2
  real(8), allocatable, dimension (:,:), target :: Deltar
  real(8), allocatable, dimension (:,:), target :: Deltar_p
  real(8), allocatable, dimension (:,:), target :: Deltar_a
  real(8), allocatable, dimension (:,:), target :: sDeltar
  real(8), allocatable, dimension (:,:,:), target :: Deltar_bound
  real(8), allocatable, dimension (:,:), target :: D1_Deltar
  real(8), allocatable, dimension (:,:), target :: DA_Deltar
  real(8), allocatable, dimension (:,:), target :: Deltar0
  real(8), allocatable, dimension (:,:), target :: DD_Deltar
  real(8), allocatable, dimension (:,:), target :: DeltaAB
  real(8), allocatable, dimension (:,:), target :: D1_DeltaAB
  real(8), allocatable, dimension (:,:), target :: lambda
  real(8), allocatable, dimension (:,:), target :: lambda_p
  real(8), allocatable, dimension (:,:), target :: lambda_a
  real(8), allocatable, dimension (:,:), target :: slambda
  real(8), allocatable, dimension (:,:,:), target :: lambda_bound
  real(8), allocatable, dimension (:,:), target :: D1_lambda
  real(8), allocatable, dimension (:,:), target :: D2_lambda
  real(8), allocatable, dimension (:,:), target :: DA_lambda
  real(8), allocatable, dimension (:,:), target :: Klambda
  real(8), allocatable, dimension (:,:), target :: Klambda_p
  real(8), allocatable, dimension (:,:), target :: Klambda_a
  real(8), allocatable, dimension (:,:), target :: sKlambda
  real(8), allocatable, dimension (:,:,:), target :: Klambda_bound
  real(8), allocatable, dimension (:,:), target :: D1_Klambda
  real(8), allocatable, dimension (:,:), target :: DA_Klambda
  real(8), allocatable, dimension (:,:), target :: lambda2
  real(8), allocatable, dimension (:,:), target :: lambda2_p
  real(8), allocatable, dimension (:,:), target :: lambda2_a
  real(8), allocatable, dimension (:,:), target :: slambda2
  real(8), allocatable, dimension (:,:,:), target :: lambda2_bound
  real(8), allocatable, dimension (:,:), target :: D1_lambda2
  real(8), allocatable, dimension (:,:), target :: D2_lambda2
  real(8), allocatable, dimension (:,:), target :: DA_lambda2
  real(8), allocatable, dimension (:,:), target :: Klambda2
  real(8), allocatable, dimension (:,:), target :: Klambda2_p
  real(8), allocatable, dimension (:,:), target :: Klambda2_a
  real(8), allocatable, dimension (:,:), target :: sKlambda2
  real(8), allocatable, dimension (:,:,:), target :: Klambda2_bound
  real(8), allocatable, dimension (:,:), target :: D1_Klambda2
  real(8), allocatable, dimension (:,:), target :: DA_Klambda2
  real(8), allocatable, dimension (:,:), target :: RICA
  real(8), allocatable, dimension (:,:), target :: RSCAL
  real(8), allocatable, dimension (:,:), target :: z4theta
  real(8), allocatable, dimension (:,:), target :: z4theta_p
  real(8), allocatable, dimension (:,:), target :: z4theta_a
  real(8), allocatable, dimension (:,:), target :: sz4theta
  real(8), allocatable, dimension (:,:,:), target :: z4theta_bound
  real(8), allocatable, dimension (:,:), target :: D1_z4theta
  real(8), allocatable, dimension (:,:), target :: DA_z4theta
  real(8), allocatable, dimension (:,:), target :: EWEYLA
  real(8), allocatable, dimension (:,:), target :: EWEYLB
  real(8), allocatable, dimension (:,:), target :: invariantI
  real(8), allocatable, dimension (:,:), target :: invariantJ
  real(8), allocatable, dimension (:,:), target :: Ricci4D
  real(8), allocatable, dimension (:,:), target :: Ricci4D_E
  real(8), allocatable, dimension (:,:), target :: ham
  real(8), allocatable, dimension (:,:), target :: hamabs
  real(8), allocatable, dimension (:,:), target :: mom
  real(8), allocatable, dimension (:,:), target :: momabs
  real(8), allocatable, dimension (:,:), target :: CDeltar
  real(8), allocatable, dimension (:,:), target :: Clambda
  real(8), allocatable, dimension (:,:), target :: CKlambda
  real(8), allocatable, dimension (:,:), target :: virial1
  real(8), allocatable, dimension (:,:), target :: virial2
  real(8), allocatable, dimension (:,:), target :: expansion
  real(8), allocatable, dimension (:,:), target :: expansion_in
  real(8), allocatable, dimension (:,:), target :: vlight
  real(8), allocatable, dimension (:,:), target :: vgauge
  real(8), allocatable, dimension (:,:), target :: wp_gauge
  real(8), allocatable, dimension (:,:), target :: wm_gauge
  real(8), allocatable, dimension (:,:), target :: wp_eta
  real(8), allocatable, dimension (:,:), target :: wm_eta
  real(8), allocatable, dimension (:,:), target :: wDelta
  real(8), allocatable, dimension (:,:), target :: rho
  real(8), allocatable, dimension (:,:), target :: JA
  real(8), allocatable, dimension (:,:), target :: SAA
  real(8), allocatable, dimension (:,:), target :: SBB
  real(8), allocatable, dimension (:,:), target :: trS
  real(8), allocatable, dimension (:,:), target :: SLL
  real(8), allocatable, dimension (:,:), target :: rho_r2
  real(8), allocatable, dimension (:,:), target :: mass_sch
  real(8), allocatable, dimension (:,:), target :: mass_int
  real(8), allocatable, dimension (:,:), target :: mass_rn
  real(8), allocatable, dimension (:,:), target :: Kodama_mass
  real(8), allocatable, dimension (:,:), target :: P_Kodama
  real(8), allocatable, dimension (:,:), target :: P_Kodama_p
  real(8), allocatable, dimension (:,:), target :: P_Kodama_a
  real(8), allocatable, dimension (:,:), target :: sP_Kodama
  real(8), allocatable, dimension (:,:,:), target :: P_Kodama_bound
  real(8), allocatable, dimension (:,:), target :: rho_int
  real(8), allocatable, dimension (:,:), target :: compactness
  real(8), allocatable, dimension (:,:), target :: trumpet_u
  real(8), allocatable, dimension (:,:), target :: trumpet_v
  real(8), allocatable, dimension (:,:), target :: scalar_phi
  real(8), allocatable, dimension (:,:), target :: scalar_phi_p
  real(8), allocatable, dimension (:,:), target :: scalar_phi_a
  real(8), allocatable, dimension (:,:), target :: sscalar_phi
  real(8), allocatable, dimension (:,:,:), target :: scalar_phi_bound
  real(8), allocatable, dimension (:,:), target :: D1_scalar_phi
  real(8), allocatable, dimension (:,:), target :: D2_scalar_phi
  real(8), allocatable, dimension (:,:), target :: DA_scalar_phi
  real(8), allocatable, dimension (:,:), target :: scalar_xi
  real(8), allocatable, dimension (:,:), target :: scalar_xi_p
  real(8), allocatable, dimension (:,:), target :: scalar_xi_a
  real(8), allocatable, dimension (:,:), target :: sscalar_xi
  real(8), allocatable, dimension (:,:,:), target :: scalar_xi_bound
  real(8), allocatable, dimension (:,:), target :: scalar_pi
  real(8), allocatable, dimension (:,:), target :: scalar_pi_p
  real(8), allocatable, dimension (:,:), target :: scalar_pi_a
  real(8), allocatable, dimension (:,:), target :: sscalar_pi
  real(8), allocatable, dimension (:,:,:), target :: scalar_pi_bound
  real(8), allocatable, dimension (:,:), target :: D1_scalar_xi
  real(8), allocatable, dimension (:,:), target :: D1_scalar_pi
  real(8), allocatable, dimension (:,:), target :: DA_scalar_xi
  real(8), allocatable, dimension (:,:), target :: DA_scalar_pi
  real(8), allocatable, dimension (:,:), target :: scalar_V
  real(8), allocatable, dimension (:,:), target :: scalar_VP
  real(8), allocatable, dimension (:,:), target :: wp_scalar
  real(8), allocatable, dimension (:,:), target :: wm_scalar
  real(8), allocatable, dimension (:,:), target :: ghost_phi
  real(8), allocatable, dimension (:,:), target :: ghost_phi_p
  real(8), allocatable, dimension (:,:), target :: ghost_phi_a
  real(8), allocatable, dimension (:,:), target :: sghost_phi
  real(8), allocatable, dimension (:,:,:), target :: ghost_phi_bound
  real(8), allocatable, dimension (:,:), target :: D1_ghost_phi
  real(8), allocatable, dimension (:,:), target :: D2_ghost_phi
  real(8), allocatable, dimension (:,:), target :: DA_ghost_phi
  real(8), allocatable, dimension (:,:), target :: ghost_xi
  real(8), allocatable, dimension (:,:), target :: ghost_xi_p
  real(8), allocatable, dimension (:,:), target :: ghost_xi_a
  real(8), allocatable, dimension (:,:), target :: sghost_xi
  real(8), allocatable, dimension (:,:,:), target :: ghost_xi_bound
  real(8), allocatable, dimension (:,:), target :: ghost_pi
  real(8), allocatable, dimension (:,:), target :: ghost_pi_p
  real(8), allocatable, dimension (:,:), target :: ghost_pi_a
  real(8), allocatable, dimension (:,:), target :: sghost_pi
  real(8), allocatable, dimension (:,:,:), target :: ghost_pi_bound
  real(8), allocatable, dimension (:,:), target :: D1_ghost_xi
  real(8), allocatable, dimension (:,:), target :: D1_ghost_pi
  real(8), allocatable, dimension (:,:), target :: DA_ghost_xi
  real(8), allocatable, dimension (:,:), target :: DA_ghost_pi
  real(8), allocatable, dimension (:,:), target :: ghost_V
  real(8), allocatable, dimension (:,:), target :: ghost_VP
  real(8), allocatable, dimension (:,:), target :: complexghost_phiR
  real(8), allocatable, dimension (:,:), target :: complexghost_phiR_p
  real(8), allocatable, dimension (:,:), target :: complexghost_phiR_a
  real(8), allocatable, dimension (:,:), target :: scomplexghost_phiR
  real(8), allocatable, dimension (:,:,:), target :: complexghost_phiR_bound
  real(8), allocatable, dimension (:,:), target :: complexghost_phiI
  real(8), allocatable, dimension (:,:), target :: complexghost_phiI_p
  real(8), allocatable, dimension (:,:), target :: complexghost_phiI_a
  real(8), allocatable, dimension (:,:), target :: scomplexghost_phiI
  real(8), allocatable, dimension (:,:,:), target :: complexghost_phiI_bound
  real(8), allocatable, dimension (:,:), target :: D1_complexghost_phiR
  real(8), allocatable, dimension (:,:), target :: D2_complexghost_phiR
  real(8), allocatable, dimension (:,:), target :: DA_complexghost_phiR
  real(8), allocatable, dimension (:,:), target :: D1_complexghost_phiI
  real(8), allocatable, dimension (:,:), target :: D2_complexghost_phiI
  real(8), allocatable, dimension (:,:), target :: DA_complexghost_phiI
  real(8), allocatable, dimension (:,:), target :: complexghost_xiR
  real(8), allocatable, dimension (:,:), target :: complexghost_xiR_p
  real(8), allocatable, dimension (:,:), target :: complexghost_xiR_a
  real(8), allocatable, dimension (:,:), target :: scomplexghost_xiR
  real(8), allocatable, dimension (:,:,:), target :: complexghost_xiR_bound
  real(8), allocatable, dimension (:,:), target :: complexghost_xiI
  real(8), allocatable, dimension (:,:), target :: complexghost_xiI_p
  real(8), allocatable, dimension (:,:), target :: complexghost_xiI_a
  real(8), allocatable, dimension (:,:), target :: scomplexghost_xiI
  real(8), allocatable, dimension (:,:,:), target :: complexghost_xiI_bound
  real(8), allocatable, dimension (:,:), target :: complexghost_piR
  real(8), allocatable, dimension (:,:), target :: complexghost_piR_p
  real(8), allocatable, dimension (:,:), target :: complexghost_piR_a
  real(8), allocatable, dimension (:,:), target :: scomplexghost_piR
  real(8), allocatable, dimension (:,:,:), target :: complexghost_piR_bound
  real(8), allocatable, dimension (:,:), target :: complexghost_piI
  real(8), allocatable, dimension (:,:), target :: complexghost_piI_p
  real(8), allocatable, dimension (:,:), target :: complexghost_piI_a
  real(8), allocatable, dimension (:,:), target :: scomplexghost_piI
  real(8), allocatable, dimension (:,:,:), target :: complexghost_piI_bound
  real(8), allocatable, dimension (:,:), target :: D1_complexghost_xiR
  real(8), allocatable, dimension (:,:), target :: D1_complexghost_xiI
  real(8), allocatable, dimension (:,:), target :: DA_complexghost_xiR
  real(8), allocatable, dimension (:,:), target :: DA_complexghost_xiI
  real(8), allocatable, dimension (:,:), target :: D1_complexghost_piR
  real(8), allocatable, dimension (:,:), target :: D1_complexghost_piI
  real(8), allocatable, dimension (:,:), target :: DA_complexghost_piR
  real(8), allocatable, dimension (:,:), target :: DA_complexghost_piI
  real(8), allocatable, dimension (:,:), target :: complexghost_V
  real(8), allocatable, dimension (:,:), target :: complexghost_VPR
  real(8), allocatable, dimension (:,:), target :: complexghost_VPI
  real(8), allocatable, dimension (:,:), target :: complexghost_phi_norm
  real(8), allocatable, dimension (:,:), target :: complex_rhotot
  real(8), allocatable, dimension (:,:), target :: complex_phiR
  real(8), allocatable, dimension (:,:), target :: complex_phiR_p
  real(8), allocatable, dimension (:,:), target :: complex_phiR_a
  real(8), allocatable, dimension (:,:), target :: scomplex_phiR
  real(8), allocatable, dimension (:,:,:), target :: complex_phiR_bound
  real(8), allocatable, dimension (:,:), target :: complex_phiI
  real(8), allocatable, dimension (:,:), target :: complex_phiI_p
  real(8), allocatable, dimension (:,:), target :: complex_phiI_a
  real(8), allocatable, dimension (:,:), target :: scomplex_phiI
  real(8), allocatable, dimension (:,:,:), target :: complex_phiI_bound
  real(8), allocatable, dimension (:,:), target :: D1_complex_phiR
  real(8), allocatable, dimension (:,:), target :: D2_complex_phiR
  real(8), allocatable, dimension (:,:), target :: DA_complex_phiR
  real(8), allocatable, dimension (:,:), target :: D1_complex_phiI
  real(8), allocatable, dimension (:,:), target :: D2_complex_phiI
  real(8), allocatable, dimension (:,:), target :: DA_complex_phiI
  real(8), allocatable, dimension (:,:), target :: complex_xiR
  real(8), allocatable, dimension (:,:), target :: complex_xiR_p
  real(8), allocatable, dimension (:,:), target :: complex_xiR_a
  real(8), allocatable, dimension (:,:), target :: scomplex_xiR
  real(8), allocatable, dimension (:,:,:), target :: complex_xiR_bound
  real(8), allocatable, dimension (:,:), target :: complex_xiI
  real(8), allocatable, dimension (:,:), target :: complex_xiI_p
  real(8), allocatable, dimension (:,:), target :: complex_xiI_a
  real(8), allocatable, dimension (:,:), target :: scomplex_xiI
  real(8), allocatable, dimension (:,:,:), target :: complex_xiI_bound
  real(8), allocatable, dimension (:,:), target :: complex_piR
  real(8), allocatable, dimension (:,:), target :: complex_piR_p
  real(8), allocatable, dimension (:,:), target :: complex_piR_a
  real(8), allocatable, dimension (:,:), target :: scomplex_piR
  real(8), allocatable, dimension (:,:,:), target :: complex_piR_bound
  real(8), allocatable, dimension (:,:), target :: complex_piI
  real(8), allocatable, dimension (:,:), target :: complex_piI_p
  real(8), allocatable, dimension (:,:), target :: complex_piI_a
  real(8), allocatable, dimension (:,:), target :: scomplex_piI
  real(8), allocatable, dimension (:,:,:), target :: complex_piI_bound
  real(8), allocatable, dimension (:,:), target :: complex_gxiR
  real(8), allocatable, dimension (:,:), target :: complex_gxiI
  real(8), allocatable, dimension (:,:), target :: complex_gpiR
  real(8), allocatable, dimension (:,:), target :: complex_gpiI
  real(8), allocatable, dimension (:,:), target :: D1_complex_xiR
  real(8), allocatable, dimension (:,:), target :: D1_complex_xiI
  real(8), allocatable, dimension (:,:), target :: DA_complex_xiR
  real(8), allocatable, dimension (:,:), target :: DA_complex_xiI
  real(8), allocatable, dimension (:,:), target :: D1_complex_piR
  real(8), allocatable, dimension (:,:), target :: D1_complex_piI
  real(8), allocatable, dimension (:,:), target :: DA_complex_piR
  real(8), allocatable, dimension (:,:), target :: DA_complex_piI
  real(8), allocatable, dimension (:,:), target :: complex_V
  real(8), allocatable, dimension (:,:), target :: complex_VPR
  real(8), allocatable, dimension (:,:), target :: complex_VPI
  real(8), allocatable, dimension (:,:), target :: complex_phi_norm
  real(8), allocatable, dimension (:,:), target :: complex_Bdens
  real(8), allocatable, dimension (:,:), target :: complex_Bdens_r2
  real(8), allocatable, dimension (:,:), target :: complex_Bflux
  real(8), allocatable, dimension (:,:), target :: complex_NB
  real(8), allocatable, dimension (:,:), target :: complex_phiaux
  real(8), allocatable, dimension (:,:), target :: complex_phiR_l0
  real(8), allocatable, dimension (:,:), target :: complex_phiR_l1
  real(8), allocatable, dimension (:,:), target :: complex_phiR_l2
  real(8), allocatable, dimension (:,:), target :: complex_phiR_l3
  real(8), allocatable, dimension (:,:), target :: nonmin_phi
  real(8), allocatable, dimension (:,:), target :: nonmin_phi_p
  real(8), allocatable, dimension (:,:), target :: nonmin_phi_a
  real(8), allocatable, dimension (:,:), target :: snonmin_phi
  real(8), allocatable, dimension (:,:,:), target :: nonmin_phi_bound
  real(8), allocatable, dimension (:,:), target :: D1_nonmin_phi
  real(8), allocatable, dimension (:,:), target :: D2_nonmin_phi
  real(8), allocatable, dimension (:,:), target :: DA_nonmin_phi
  real(8), allocatable, dimension (:,:), target :: nonmin_xi
  real(8), allocatable, dimension (:,:), target :: nonmin_xi_p
  real(8), allocatable, dimension (:,:), target :: nonmin_xi_a
  real(8), allocatable, dimension (:,:), target :: snonmin_xi
  real(8), allocatable, dimension (:,:,:), target :: nonmin_xi_bound
  real(8), allocatable, dimension (:,:), target :: nonmin_pi
  real(8), allocatable, dimension (:,:), target :: nonmin_pi_p
  real(8), allocatable, dimension (:,:), target :: nonmin_pi_a
  real(8), allocatable, dimension (:,:), target :: snonmin_pi
  real(8), allocatable, dimension (:,:,:), target :: nonmin_pi_bound
  real(8), allocatable, dimension (:,:), target :: D1_nonmin_xi
  real(8), allocatable, dimension (:,:), target :: D1_nonmin_pi
  real(8), allocatable, dimension (:,:), target :: DA_nonmin_xi
  real(8), allocatable, dimension (:,:), target :: DA_nonmin_pi
  real(8), allocatable, dimension (:,:), target :: nonmin_V
  real(8), allocatable, dimension (:,:), target :: nonmin_VP
  real(8), allocatable, dimension (:,:), target :: nonmin_Q
  real(8), allocatable, dimension (:,:), target :: nonmin_f
  real(8), allocatable, dimension (:,:), target :: nonmin_fp
  real(8), allocatable, dimension (:,:), target :: nonmin_fpp
  real(8), allocatable, dimension (:,:), target :: nonmin_rhs
  real(8), allocatable, dimension (:,:), target :: DD_nonmin_xir
  real(8), allocatable, dimension (:,:), target :: electric
  real(8), allocatable, dimension (:,:), target :: electric_p
  real(8), allocatable, dimension (:,:), target :: electric_a
  real(8), allocatable, dimension (:,:), target :: selectric
  real(8), allocatable, dimension (:,:,:), target :: electric_bound
  real(8), allocatable, dimension (:,:), target :: D1_electric
  real(8), allocatable, dimension (:,:), target :: DA_electric
  real(8), allocatable, dimension (:,:), target :: ePhi
  real(8), allocatable, dimension (:,:), target :: ePhi_p
  real(8), allocatable, dimension (:,:), target :: ePhi_a
  real(8), allocatable, dimension (:,:), target :: sePhi
  real(8), allocatable, dimension (:,:,:), target :: ePhi_bound
  real(8), allocatable, dimension (:,:), target :: D1_ePhi
  real(8), allocatable, dimension (:,:), target :: DA_ePhi
  real(8), allocatable, dimension (:,:), target :: eAr
  real(8), allocatable, dimension (:,:), target :: eAr_p
  real(8), allocatable, dimension (:,:), target :: eAr_a
  real(8), allocatable, dimension (:,:), target :: seAr
  real(8), allocatable, dimension (:,:,:), target :: eAr_bound
  real(8), allocatable, dimension (:,:), target :: D1_eAr
  real(8), allocatable, dimension (:,:), target :: DA_eAr
  real(8), allocatable, dimension (:,:), target :: eF
  real(8), allocatable, dimension (:,:), target :: D1_eF
  real(8), allocatable, dimension (:,:), target :: eH
  real(8), allocatable, dimension (:,:), target :: D1_eH
  real(8), allocatable, dimension (:,:), target :: echarge
  real(8), allocatable, dimension (:,:), target :: ecurrent
  real(8), allocatable, dimension (:,:), target :: Celectric
  real(8), allocatable, dimension (:,:), target :: eQ_int
  real(8), allocatable, dimension (:,:), target :: eQ_surf
  real(8), allocatable, dimension (:,:), target :: wp_electric
  real(8), allocatable, dimension (:,:), target :: wm_electric
  real(8), allocatable, dimension (:,:), target :: procaE
  real(8), allocatable, dimension (:,:), target :: procaE_p
  real(8), allocatable, dimension (:,:), target :: procaE_a
  real(8), allocatable, dimension (:,:), target :: sprocaE
  real(8), allocatable, dimension (:,:,:), target :: procaE_bound
  real(8), allocatable, dimension (:,:), target :: D1_procaE
  real(8), allocatable, dimension (:,:), target :: DA_procaE
  real(8), allocatable, dimension (:,:), target :: procaPhi
  real(8), allocatable, dimension (:,:), target :: procaPhi_p
  real(8), allocatable, dimension (:,:), target :: procaPhi_a
  real(8), allocatable, dimension (:,:), target :: sprocaPhi
  real(8), allocatable, dimension (:,:,:), target :: procaPhi_bound
  real(8), allocatable, dimension (:,:), target :: D1_procaPhi
  real(8), allocatable, dimension (:,:), target :: DA_procaPhi
  real(8), allocatable, dimension (:,:), target :: procaA
  real(8), allocatable, dimension (:,:), target :: procaA_p
  real(8), allocatable, dimension (:,:), target :: procaA_a
  real(8), allocatable, dimension (:,:), target :: sprocaA
  real(8), allocatable, dimension (:,:,:), target :: procaA_bound
  real(8), allocatable, dimension (:,:), target :: D1_procaA
  real(8), allocatable, dimension (:,:), target :: DA_procaA
  real(8), allocatable, dimension (:,:), target :: procaF
  real(8), allocatable, dimension (:,:), target :: D1_procaF
  real(8), allocatable, dimension (:,:), target :: procaH
  real(8), allocatable, dimension (:,:), target :: D1_procaH
  real(8), allocatable, dimension (:,:), target :: procaV
  real(8), allocatable, dimension (:,:), target :: Cproca
  real(8), allocatable, dimension (:,:), target :: wp_proca
  real(8), allocatable, dimension (:,:), target :: wm_proca
  real(8), allocatable, dimension (:,:), target :: cprocaE_R
  real(8), allocatable, dimension (:,:), target :: cprocaE_R_p
  real(8), allocatable, dimension (:,:), target :: cprocaE_R_a
  real(8), allocatable, dimension (:,:), target :: scprocaE_R
  real(8), allocatable, dimension (:,:,:), target :: cprocaE_R_bound
  real(8), allocatable, dimension (:,:), target :: D1_cprocaE_R
  real(8), allocatable, dimension (:,:), target :: DA_cprocaE_R
  real(8), allocatable, dimension (:,:), target :: cprocaE_I
  real(8), allocatable, dimension (:,:), target :: cprocaE_I_p
  real(8), allocatable, dimension (:,:), target :: cprocaE_I_a
  real(8), allocatable, dimension (:,:), target :: scprocaE_I
  real(8), allocatable, dimension (:,:,:), target :: cprocaE_I_bound
  real(8), allocatable, dimension (:,:), target :: D1_cprocaE_I
  real(8), allocatable, dimension (:,:), target :: DA_cprocaE_I
  real(8), allocatable, dimension (:,:), target :: cprocaXi_R
  real(8), allocatable, dimension (:,:), target :: cprocaXi_R_p
  real(8), allocatable, dimension (:,:), target :: cprocaXi_R_a
  real(8), allocatable, dimension (:,:), target :: scprocaXi_R
  real(8), allocatable, dimension (:,:,:), target :: cprocaXi_R_bound
  real(8), allocatable, dimension (:,:), target :: D1_cprocaXi_R
  real(8), allocatable, dimension (:,:), target :: DA_cprocaXi_R
  real(8), allocatable, dimension (:,:), target :: cprocaXi_I
  real(8), allocatable, dimension (:,:), target :: cprocaXi_I_p
  real(8), allocatable, dimension (:,:), target :: cprocaXi_I_a
  real(8), allocatable, dimension (:,:), target :: scprocaXi_I
  real(8), allocatable, dimension (:,:,:), target :: cprocaXi_I_bound
  real(8), allocatable, dimension (:,:), target :: D1_cprocaXi_I
  real(8), allocatable, dimension (:,:), target :: DA_cprocaXi_I
  real(8), allocatable, dimension (:,:), target :: cprocaPhi_R
  real(8), allocatable, dimension (:,:), target :: cprocaPhi_R_p
  real(8), allocatable, dimension (:,:), target :: cprocaPhi_R_a
  real(8), allocatable, dimension (:,:), target :: scprocaPhi_R
  real(8), allocatable, dimension (:,:,:), target :: cprocaPhi_R_bound
  real(8), allocatable, dimension (:,:), target :: D1_cprocaPhi_R
  real(8), allocatable, dimension (:,:), target :: DA_cprocaPhi_R
  real(8), allocatable, dimension (:,:), target :: cprocaPhi_I
  real(8), allocatable, dimension (:,:), target :: cprocaPhi_I_p
  real(8), allocatable, dimension (:,:), target :: cprocaPhi_I_a
  real(8), allocatable, dimension (:,:), target :: scprocaPhi_I
  real(8), allocatable, dimension (:,:,:), target :: cprocaPhi_I_bound
  real(8), allocatable, dimension (:,:), target :: D1_cprocaPhi_I
  real(8), allocatable, dimension (:,:), target :: DA_cprocaPhi_I
  real(8), allocatable, dimension (:,:), target :: cprocaA_R
  real(8), allocatable, dimension (:,:), target :: cprocaA_R_p
  real(8), allocatable, dimension (:,:), target :: cprocaA_R_a
  real(8), allocatable, dimension (:,:), target :: scprocaA_R
  real(8), allocatable, dimension (:,:,:), target :: cprocaA_R_bound
  real(8), allocatable, dimension (:,:), target :: D1_cprocaA_R
  real(8), allocatable, dimension (:,:), target :: DA_cprocaA_R
  real(8), allocatable, dimension (:,:), target :: cprocaA_I
  real(8), allocatable, dimension (:,:), target :: cprocaA_I_p
  real(8), allocatable, dimension (:,:), target :: cprocaA_I_a
  real(8), allocatable, dimension (:,:), target :: scprocaA_I
  real(8), allocatable, dimension (:,:,:), target :: cprocaA_I_bound
  real(8), allocatable, dimension (:,:), target :: D1_cprocaA_I
  real(8), allocatable, dimension (:,:), target :: DA_cprocaA_I
  real(8), allocatable, dimension (:,:), target :: cprocaF_R
  real(8), allocatable, dimension (:,:), target :: D1_cprocaF_R
  real(8), allocatable, dimension (:,:), target :: cprocaF_I
  real(8), allocatable, dimension (:,:), target :: D1_cprocaF_I
  real(8), allocatable, dimension (:,:), target :: cprocaH_R
  real(8), allocatable, dimension (:,:), target :: D1_cprocaH_R
  real(8), allocatable, dimension (:,:), target :: cprocaH_I
  real(8), allocatable, dimension (:,:), target :: D1_cprocaH_I
  real(8), allocatable, dimension (:,:), target :: cprocaB_R
  real(8), allocatable, dimension (:,:), target :: cprocaB_R_p
  real(8), allocatable, dimension (:,:), target :: cprocaB_R_a
  real(8), allocatable, dimension (:,:), target :: scprocaB_R
  real(8), allocatable, dimension (:,:,:), target :: cprocaB_R_bound
  real(8), allocatable, dimension (:,:), target :: D1_cprocaB_R
  real(8), allocatable, dimension (:,:), target :: D2_cprocaB_R
  real(8), allocatable, dimension (:,:), target :: DA_cprocaB_R
  real(8), allocatable, dimension (:,:), target :: cprocaB_I
  real(8), allocatable, dimension (:,:), target :: cprocaB_I_p
  real(8), allocatable, dimension (:,:), target :: cprocaB_I_a
  real(8), allocatable, dimension (:,:), target :: scprocaB_I
  real(8), allocatable, dimension (:,:,:), target :: cprocaB_I_bound
  real(8), allocatable, dimension (:,:), target :: D1_cprocaB_I
  real(8), allocatable, dimension (:,:), target :: D2_cprocaB_I
  real(8), allocatable, dimension (:,:), target :: DA_cprocaB_I
  real(8), allocatable, dimension (:,:), target :: cprocaG_R
  real(8), allocatable, dimension (:,:), target :: cprocaG_R_p
  real(8), allocatable, dimension (:,:), target :: cprocaG_R_a
  real(8), allocatable, dimension (:,:), target :: scprocaG_R
  real(8), allocatable, dimension (:,:,:), target :: cprocaG_R_bound
  real(8), allocatable, dimension (:,:), target :: D1_cprocaG_R
  real(8), allocatable, dimension (:,:), target :: DA_cprocaG_R
  real(8), allocatable, dimension (:,:), target :: cprocaG_I
  real(8), allocatable, dimension (:,:), target :: cprocaG_I_p
  real(8), allocatable, dimension (:,:), target :: cprocaG_I_a
  real(8), allocatable, dimension (:,:), target :: scprocaG_I
  real(8), allocatable, dimension (:,:,:), target :: cprocaG_I_bound
  real(8), allocatable, dimension (:,:), target :: D1_cprocaG_I
  real(8), allocatable, dimension (:,:), target :: DA_cprocaG_I
  real(8), allocatable, dimension (:,:), target :: cprocaL_R
  real(8), allocatable, dimension (:,:), target :: cprocaL_R_p
  real(8), allocatable, dimension (:,:), target :: cprocaL_R_a
  real(8), allocatable, dimension (:,:), target :: scprocaL_R
  real(8), allocatable, dimension (:,:,:), target :: cprocaL_R_bound
  real(8), allocatable, dimension (:,:), target :: cprocaL_I
  real(8), allocatable, dimension (:,:), target :: cprocaL_I_p
  real(8), allocatable, dimension (:,:), target :: cprocaL_I_a
  real(8), allocatable, dimension (:,:), target :: scprocaL_I
  real(8), allocatable, dimension (:,:,:), target :: cprocaL_I_bound
  real(8), allocatable, dimension (:,:), target :: Ccomplexproca_R
  real(8), allocatable, dimension (:,:), target :: Ccomplexproca_I
  real(8), allocatable, dimension (:,:), target :: cprocaPhi_norm
  real(8), allocatable, dimension (:,:), target :: cprocaA_norm
  real(8), allocatable, dimension (:,:), target :: cprocaB_norm
  real(8), allocatable, dimension (:,:), target :: cprocaE_norm
  real(8), allocatable, dimension (:,:), target :: cprocaXi_norm
  real(8), allocatable, dimension (:,:), target :: Ccomplexproca_norm
  real(8), allocatable, dimension (:,:), target :: cproca_Qdens
  real(8), allocatable, dimension (:,:), target :: cproca_Qdens_r2
  real(8), allocatable, dimension (:,:), target :: cproca_Qflux
  real(8), allocatable, dimension (:,:), target :: cproca_Qint
  real(8), allocatable, dimension (:,:), target :: dirac_FR
  real(8), allocatable, dimension (:,:), target :: dirac_FR_p
  real(8), allocatable, dimension (:,:), target :: dirac_FR_a
  real(8), allocatable, dimension (:,:), target :: sdirac_FR
  real(8), allocatable, dimension (:,:,:), target :: dirac_FR_bound
  real(8), allocatable, dimension (:,:), target :: dirac_FI
  real(8), allocatable, dimension (:,:), target :: dirac_FI_p
  real(8), allocatable, dimension (:,:), target :: dirac_FI_a
  real(8), allocatable, dimension (:,:), target :: sdirac_FI
  real(8), allocatable, dimension (:,:,:), target :: dirac_FI_bound
  real(8), allocatable, dimension (:,:), target :: dirac_GR
  real(8), allocatable, dimension (:,:), target :: dirac_GR_p
  real(8), allocatable, dimension (:,:), target :: dirac_GR_a
  real(8), allocatable, dimension (:,:), target :: sdirac_GR
  real(8), allocatable, dimension (:,:,:), target :: dirac_GR_bound
  real(8), allocatable, dimension (:,:), target :: dirac_GI
  real(8), allocatable, dimension (:,:), target :: dirac_GI_p
  real(8), allocatable, dimension (:,:), target :: dirac_GI_a
  real(8), allocatable, dimension (:,:), target :: sdirac_GI
  real(8), allocatable, dimension (:,:,:), target :: dirac_GI_bound
  real(8), allocatable, dimension (:,:), target :: D1_dirac_FR
  real(8), allocatable, dimension (:,:), target :: D1_dirac_FI
  real(8), allocatable, dimension (:,:), target :: DA_dirac_FR
  real(8), allocatable, dimension (:,:), target :: DA_dirac_FI
  real(8), allocatable, dimension (:,:), target :: D1_dirac_GR
  real(8), allocatable, dimension (:,:), target :: D1_dirac_GI
  real(8), allocatable, dimension (:,:), target :: DA_dirac_GR
  real(8), allocatable, dimension (:,:), target :: DA_dirac_GI
  real(8), allocatable, dimension (:,:), target :: dirac_HR
  real(8), allocatable, dimension (:,:), target :: dirac_HI
  real(8), allocatable, dimension (:,:), target :: D1_dirac_HR
  real(8), allocatable, dimension (:,:), target :: D1_dirac_HI
  real(8), allocatable, dimension (:,:), target :: dirac_PiFR
  real(8), allocatable, dimension (:,:), target :: dirac_PiFI
  real(8), allocatable, dimension (:,:), target :: dirac_PiGR
  real(8), allocatable, dimension (:,:), target :: dirac_PiGI
  real(8), allocatable, dimension (:,:), target :: dirac_F_norm
  real(8), allocatable, dimension (:,:), target :: dirac_G_norm
  real(8), allocatable, dimension (:,:), target :: dirac_dens
  real(8), allocatable, dimension (:,:), target :: dirac_flux
  real(8), allocatable, dimension (:,:), target :: dirac_Nint
  real(8), allocatable, dimension (:,:), target :: wpR_dirac
  real(8), allocatable, dimension (:,:), target :: wmR_dirac
  real(8), allocatable, dimension (:,:), target :: wpI_dirac
  real(8), allocatable, dimension (:,:), target :: wmI_dirac
  real(8), allocatable, dimension (:,:), target :: dust_rho
  real(8), allocatable, dimension (:,:), target :: dust_v
  real(8), allocatable, dimension (:,:), target :: dust_W
  real(8), allocatable, dimension (:,:), target :: dust_cD
  real(8), allocatable, dimension (:,:), target :: dust_cD_p
  real(8), allocatable, dimension (:,:), target :: dust_cD_a
  real(8), allocatable, dimension (:,:), target :: sdust_cD
  real(8), allocatable, dimension (:,:,:), target :: dust_cD_bound
  real(8), allocatable, dimension (:,:), target :: D1_dust_cD
  real(8), allocatable, dimension (:,:), target :: DA_dust_cD
  real(8), allocatable, dimension (:,:), target :: dust_cE
  real(8), allocatable, dimension (:,:), target :: dust_cE_p
  real(8), allocatable, dimension (:,:), target :: dust_cE_a
  real(8), allocatable, dimension (:,:), target :: sdust_cE
  real(8), allocatable, dimension (:,:,:), target :: dust_cE_bound
  real(8), allocatable, dimension (:,:), target :: D1_dust_cE
  real(8), allocatable, dimension (:,:), target :: DA_dust_cE
  real(8), allocatable, dimension (:,:), target :: dust_cS
  real(8), allocatable, dimension (:,:), target :: dust_cS_p
  real(8), allocatable, dimension (:,:), target :: dust_cS_a
  real(8), allocatable, dimension (:,:), target :: sdust_cS
  real(8), allocatable, dimension (:,:,:), target :: dust_cS_bound
  real(8), allocatable, dimension (:,:), target :: D1_dust_cS
  real(8), allocatable, dimension (:,:), target :: DA_dust_cS
  real(8), allocatable, dimension (:,:), target :: dust_restmass
  real(8), allocatable, dimension (:,:), target :: fluid_rho
  real(8), allocatable, dimension (:,:), target :: fluid_rhotot
  real(8), allocatable, dimension (:,:), target :: fluid_e
  real(8), allocatable, dimension (:,:), target :: fluid_p
  real(8), allocatable, dimension (:,:), target :: D1_fluid_p
  real(8), allocatable, dimension (:,:), target :: fluid_h
  real(8), allocatable, dimension (:,:), target :: fluid_v
  real(8), allocatable, dimension (:,:), target :: fluid_W
  real(8), allocatable, dimension (:,:), target :: fluid_vs
  real(8), allocatable, dimension (:,:), target :: fluid_Mach
  real(8), allocatable, dimension (:,:), target :: fluid_vcp
  real(8), allocatable, dimension (:,:), target :: fluid_vcm
  real(8), allocatable, dimension (:,:), target :: fluid_wb_rest
  real(8), allocatable, dimension (:,:), target :: fluid_wb_tot
  real(8), allocatable, dimension (:,:), target :: fluid_cD
  real(8), allocatable, dimension (:,:), target :: fluid_cD_p
  real(8), allocatable, dimension (:,:), target :: fluid_cD_a
  real(8), allocatable, dimension (:,:), target :: sfluid_cD
  real(8), allocatable, dimension (:,:,:), target :: fluid_cD_bound
  real(8), allocatable, dimension (:,:), target :: D1_fluid_cD
  real(8), allocatable, dimension (:,:), target :: DA_fluid_cD
  real(8), allocatable, dimension (:,:), target :: fluid_cE
  real(8), allocatable, dimension (:,:), target :: fluid_cE_p
  real(8), allocatable, dimension (:,:), target :: fluid_cE_a
  real(8), allocatable, dimension (:,:), target :: sfluid_cE
  real(8), allocatable, dimension (:,:,:), target :: fluid_cE_bound
  real(8), allocatable, dimension (:,:), target :: D1_fluid_cE
  real(8), allocatable, dimension (:,:), target :: DA_fluid_cE
  real(8), allocatable, dimension (:,:), target :: fluid_cS
  real(8), allocatable, dimension (:,:), target :: fluid_cS_p
  real(8), allocatable, dimension (:,:), target :: fluid_cS_a
  real(8), allocatable, dimension (:,:), target :: sfluid_cS
  real(8), allocatable, dimension (:,:,:), target :: fluid_cS_bound
  real(8), allocatable, dimension (:,:), target :: D1_fluid_cS
  real(8), allocatable, dimension (:,:), target :: DA_fluid_cS
  real(8), allocatable, dimension (:,:), target :: fluid_q
  real(8), allocatable, dimension (:,:), target :: fluid_restmass
  real(8), allocatable, dimension (:,:), target :: fluid_totalmass
  real(8), allocatable, dimension (:), target :: cosmobg_tau
  real(8), allocatable, dimension (:), target :: cosmobg_tau_p
  real(8), allocatable, dimension (:), target :: cosmobg_tau_a
  real(8), allocatable, dimension (:), target :: scosmobg_tau
  real(8), allocatable, dimension (:), target :: cosmobg_H
  real(8), allocatable, dimension (:), target :: cosmobg_H_p
  real(8), allocatable, dimension (:), target :: cosmobg_H_a
  real(8), allocatable, dimension (:), target :: scosmobg_H
  real(8), allocatable, dimension (:), target :: cosmobg_a
  real(8), allocatable, dimension (:), target :: cosmobg_a_p
  real(8), allocatable, dimension (:), target :: cosmobg_a_a
  real(8), allocatable, dimension (:), target :: scosmobg_a
  real(8), allocatable, dimension (:), target :: cosmobg_phi
  real(8), allocatable, dimension (:), target :: cosmobg_phi_p
  real(8), allocatable, dimension (:), target :: cosmobg_phi_a
  real(8), allocatable, dimension (:), target :: scosmobg_phi
  real(8), allocatable, dimension (:), target :: cosmobg_trK
  real(8), allocatable, dimension (:), target :: cosmobg_trK_p
  real(8), allocatable, dimension (:), target :: cosmobg_trK_a
  real(8), allocatable, dimension (:), target :: scosmobg_trK
  real(8), allocatable, dimension (:), target :: cosmobg_alpha
  real(8), allocatable, dimension (:), target :: cosmobg_alpha_p
  real(8), allocatable, dimension (:), target :: cosmobg_alpha_a
  real(8), allocatable, dimension (:), target :: scosmobg_alpha
  real(8), allocatable, dimension (:), target :: cosmobg_falpha
  real(8), allocatable, dimension (:), target :: cosmobg_vlight
  real(8), allocatable, dimension (:), target :: cosmobg_rho
  real(8), allocatable, dimension (:), target :: cosmobg_p
  real(8), allocatable, dimension (:,:), target :: alpha_pert
  real(8), allocatable, dimension (:,:), target :: phi_pert
  real(8), allocatable, dimension (:,:), target :: trK_pert
  real(8), allocatable, dimension (:,:), target :: rho_pert
  real(8), allocatable, dimension (:,:), target :: rho_contrast
  real(8), allocatable, dimension (:,:), target :: rho_pert_int
  real(8), allocatable, dimension (:,:), target :: rho_contrast_int
  real(8), allocatable, dimension (:,:), target :: cosmo_compactness
  real(8), allocatable, dimension (:), target :: cosmobg_scalar_phi
  real(8), allocatable, dimension (:), target :: cosmobg_scalar_phi_p
  real(8), allocatable, dimension (:), target :: cosmobg_scalar_phi_a
  real(8), allocatable, dimension (:), target :: scosmobg_scalar_phi
  real(8), allocatable, dimension (:), target :: cosmobg_scalar_pi
  real(8), allocatable, dimension (:), target :: cosmobg_scalar_pi_p
  real(8), allocatable, dimension (:), target :: cosmobg_scalar_pi_a
  real(8), allocatable, dimension (:), target :: scosmobg_scalar_pi
  real(8), allocatable, dimension (:), target :: cosmobg_scalar_V
  real(8), allocatable, dimension (:), target :: cosmobg_scalar_VP
  real(8), allocatable, dimension (:), target :: cosmobg_complex_phiR
  real(8), allocatable, dimension (:), target :: cosmobg_complex_phiR_p
  real(8), allocatable, dimension (:), target :: cosmobg_complex_phiR_a
  real(8), allocatable, dimension (:), target :: scosmobg_complex_phiR
  real(8), allocatable, dimension (:), target :: cosmobg_complex_phiI
  real(8), allocatable, dimension (:), target :: cosmobg_complex_phiI_p
  real(8), allocatable, dimension (:), target :: cosmobg_complex_phiI_a
  real(8), allocatable, dimension (:), target :: scosmobg_complex_phiI
  real(8), allocatable, dimension (:), target :: cosmobg_complex_piR
  real(8), allocatable, dimension (:), target :: cosmobg_complex_piR_p
  real(8), allocatable, dimension (:), target :: cosmobg_complex_piR_a
  real(8), allocatable, dimension (:), target :: scosmobg_complex_piR
  real(8), allocatable, dimension (:), target :: cosmobg_complex_piI
  real(8), allocatable, dimension (:), target :: cosmobg_complex_piI_p
  real(8), allocatable, dimension (:), target :: cosmobg_complex_piI_a
  real(8), allocatable, dimension (:), target :: scosmobg_complex_piI
  real(8), allocatable, dimension (:), target :: cosmobg_complex_V
  real(8), allocatable, dimension (:), target :: cosmobg_complex_VPR
  real(8), allocatable, dimension (:), target :: cosmobg_complex_VPI
  real(8), allocatable, dimension (:,:), target :: r_trans
  real(8), allocatable, dimension (:,:), target :: R_MINK
  real(8), allocatable, dimension (:,:), target :: R_MINK_P
  real(8), allocatable, dimension (:,:), target :: R_MINK_S
  real(8), allocatable, dimension (:,:), target :: T_MINK
  real(8), allocatable, dimension (:,:), target :: T_MINK_P
  real(8), allocatable, dimension (:,:), target :: T_MINK_S
  real(8), allocatable, dimension (:,:), target :: CSI_SCHWARZ
  real(8), allocatable, dimension (:,:), target :: CSI_SCHWARZ_P
  real(8), allocatable, dimension (:,:), target :: ETA_SCHWARZ
  real(8), allocatable, dimension (:,:), target :: ETA_SCHWARZ_P

  end module arrays

